package com.example.mtcbuzz;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.SocketTimeoutException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.Dialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.DialogInterface.OnClickListener;
import android.content.Intent;
import android.location.LocationManager;
import android.media.RingtoneManager;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.provider.Settings.Secure;
import android.provider.Settings.SettingNotFoundException;
import android.text.TextUtils;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.Toast;

public class MainActivity extends Activity {
	static int iflag=0;
	final Handler mHandler = new Handler();
	 
	
	private void buildAlertMessageNoGps(int i) {    
		String s=(i==1)?"We suggest you enable GPS for accurate alarms.":"We suggest you enable Location Services in High Accuracy mode, for accurate alarms.";
	    s+="If you are low on battery, remember to turn it on atleast nearer to your destination.";
		final AlertDialog.Builder builder = new AlertDialog.Builder(this);
	    builder.setMessage(s)
	           .setCancelable(false)
	           .setPositiveButton("Settings", new DialogInterface.OnClickListener() {
	               public void onClick(@SuppressWarnings("unused") final DialogInterface dialog, @SuppressWarnings("unused") final int id) {
	                   startActivity(new Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS));
	               }
	           })
	           .setNegativeButton("Never mind", new DialogInterface.OnClickListener() {
	               public void onClick(final DialogInterface dialog, @SuppressWarnings("unused") final int id) {
	                    dialog.cancel();
	                    iflag=1;
	               }
	           });
	    final AlertDialog alert = builder.create();
	    alert.setIcon(R.drawable.ic_launcher);
	    alert.show();
	}
	
	
	private void buildAlertMessageNeedsGps(int i) {    
		String s=(i==1)?"This action needs GPS.":"This action needs Location Services in High Accuracy mode.";
	    s+="You can switch it off immediately after checking the required bus stops.";
		final AlertDialog.Builder builder = new AlertDialog.Builder(this);
	    builder.setMessage(s)
	           .setCancelable(false)
	           .setPositiveButton("Settings", new DialogInterface.OnClickListener() {
	               public void onClick(@SuppressWarnings("unused") final DialogInterface dialog, @SuppressWarnings("unused") final int id) {
	                   startActivity(new Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS));
	               }
	           })
	           .setNegativeButton("DISMISS", new DialogInterface.OnClickListener() {
	               public void onClick(final DialogInterface dialog, @SuppressWarnings("unused") final int id) {
	                    dialog.cancel();
	               }
	           });
	    final AlertDialog alert = builder.create();
	    alert.setIcon(R.drawable.ic_launcher);
	    alert.show();
	}
	
	
	
	public final static String SRC_STOP = "com.example.myfirstapp.SRC_STOP";
	public final static String DEST_STOP = "com.example.myfirstapp.DEST_STOP";
	String[] stops={"100 FEET ROAD JN.","2ND WATER TANK ON SECOND","AAFS CROSS ROAD","AAYA KOLATHUR","AAYURVEDA ASHRAMAM","ABIRAMI MADAM","ADAMBAKKAM P.S","ADAYAR B.S.","ADAYAR DEPOT","ADAYAR O.T.","ADI DRAVIDAR HOSTEL","ADYAR GATE","AGARAM","AGARAM MEL","AGARAM THEN","A.G.S OFFICE COLONY","AIRFORCE STATION","ALAGESA NAGAR","ALAMADHI","DRY CATTLLE FORM","ALAMADHI OLD","ALANDUR","ALANDUR DEPOT","ALANDUR MUNICIPALITY","ALAPAKKAM","ALAPAKKAM KOOT ROAD","ALWAR THIRUNAGAR","AMARAMBEDU","AMARAMBEDU CHATRAM","AMARAMBEDU ROAD","AMARAMBEDU VILLAGE","AMBATHUR","AMBATHUR ESTATE","AMB OT","AMBEDKAR NAGAR","AMINIJIKARAI","AMMAN KULAM","AMMUR COLONY","A.M.S.HOSPITAL","ANAICUTCHE","ANAKAPUTHUR","ANANDA NAGAR","ANDAKUPPAM","ANDERSONPET","ANGADU","ANGALAMMAN KOIL","ANJATHAMMAN KOIL","ANJUGAM SCHOOL","ANNAI SIVAKAMI NAGAR","ANNAMBEDU","ANNA NAGAR","ANNA NAGAR CIRCLE","ANNA NAGAR COLONY","ANNA NAGAR EAST","ANNA NAGAR WEST","ANNA POORNA HOTEL/DAMS RD","ANNA ROAD P.O./DAMS ROAD","ANNA SQUARE","ANNA UNIVERSITY","ARAKKAMBAKKAM","ARAKKAMBAKKAM RD.JN.","ARANI","ARANVOYAL","ARANVOYAL KUPPAM","ARASANKAZHANI","ARIYALUR","ARIYAPAKKAM","ARUMANDAI RD.JN.","ARUMBAKKAM","ASHOK LAYLAND","ASHOK LEYLAND MARK.DIV.","ATHIPET I.C.F. COLONY","ATHIPET JN","ATHUPAKKAM","ATHUR","AVADI","AVADI CIRCLE","AVADI MOSQUE","AVADI ROAD JN.","A.V.CONSTRUCTION","AVVAI HOME","AYALCHERY","AYANALLUR","AYANAMBAKKAM","AYANAVARAM B.S","AYAPAKKAM","AYYAPPA NAGAR","AYYAPPAN MADAM","AYYAPPAN THANGAL","AZHINJIVAKKAM RD.JN.","AZHINJIVAKKAM VILLAGE","BALAJI NAGAR (BHARATH ENG","BEEMANTHANGAL","BESANT NAGAR","BESANTNAGAR W.TANK","BHARATHA MATHA ST","BHARATH ELECTRONICS","BHARATHI NAGAR(PERIYAR PA","BHONDHUR","BOROSIL COMPANY","BRINDAVAN COLONY","BROADWAY","BUDUR","BUILDERS INDUSTRY","BURIAL GROUND","BURMAH SHELL PETROL BUNK","BUTT ROAD","CAMP","CAMP ROAD","CEMENTRY (MANDAVELI)","CENTRAL","CHATHIRAM","CHEMBAKKAM JUNCTION","CHEMBAKKAM VILLAGE","CHEMBARAMBAKKAM","CHENGAMMAL KOOT ROAD","CHENGLEPET N.T.","CHENGLEPET O.T.","CHEPAUK","CHETPET","CHETTIMEDU","CHETTIPEDU","CHEVVAIPETTAI R.S.","CHIDAMBARAM STORES","CHINAMBEDU COLONY","CHINMAYA NAGAR","CHINNA KODUNGAIYUR","CHINNAKUVANAM","CHINNAMBEDU VILLAGE","CHIRUTHAVOOR JN.","CHITLAPAKKAM","CHITLAPAKKAM B.S","CHITTUKADU","CHOLA MANDAL","CHOOLAI MILL","CHOOLAI P.O","CHRISTIAN HOSPITAL","CHROMEPET LAKSHMIPURAM","CHROMPET","CHURCH","CIPET","C.I.T.COLONY","CLIVE BATTERY","C.M.B.T.","COLLECTOR NAGAR","CONCORDE","CONCRET COMPANY","CONVENT","CORBORUNDUM UNIVERSAL","CORONATION NAGAR","CORPN. PLAY GROUND","CORPORATION OFFICE/STERLI","CORPORATION SCHOOL/OFFICE","COWL BAZAAR","CRESCENT RESIDENTIAL H.S.","C.R.P.CROSS RD.","C.R.P.F","C.V.D.MITNAMALLEE RD.JN.","CYCLE SHOP","DASAMAHAN","DASAPRAKASH","DASARATHAPURAM","DEFENCE COLONY","DEFENCE QUARTERS","DEVANATHAN ST / MANDAVELI","DHARMAPRAKASH/PETROL BUNK","DHARMAPURAM KANDIGAI","DIDEER NAGAR","D.M.S","DOVETON","D.P.I","DR.AMBEDHAR BRIDGE","DUNLOP","DURGAS","EANNAM AGARAM","EASWARAN TEMPLE/PTC QRTS.","E.B.OFFICE","E.B.STATION","ECHANKADU","ECHANKUZHI","ECHANKUZHI /MANALI NEW TO","EGMORE","EGMORE NORTH R.S.","EKKADU CSI HOSPITAL","EKKADU KANDIGAI","EKKADU WATER TANK(TEACHER","ELANGO NAGAR OFFICER COLO","ELAVAMBEDU","ELLAIAMMAN KOIL","ELLAMPETTAI","ENAMBAKKAM","ENG.COLLEGE","ENNORE","ERAIYUR JUNCTION","ERNAKUPPMA","ERNAVOOR GATE","ETTAYAPURAM","EZHICHUR KOOT ROAD","EZHIL NAGAR","F.C.I OLD","FIRE STATION","FIVE LAMPS","FORD","FORE SHORE ESTATE","GANESH PURAM","GANGAI ADI KUPPAM","GASSGI RATE COMPANY","GEEYEE HOUSING","GEMINI P.H","G.K.M.COLONY","GNANAMOORTHY NAGAR","GNAYARU","GOLDEN FLAT","GOVARDANAGIRI","GOVERNMENT SCHOOL / HOSPI","GOVT. GIRLS H.SC","GRAND LINE","G.R.KANDIKAI","GUDUVANCHERY","GUINDY RACE COURCE OFFICE","GUINDY R.S","GUINDY TVK ESTATE","GUMMUDIPOONDI R.S.","GURUNANAK COLLEGE","GURUVOYAL KARANIBATTAI","HASTHINAPURAM","HIGH COURT","HINDUSTAL EGG. COLLEGE","HINDY VIDYALAYA","HOTEL ARUN","HOUSING BOARD","H.V.F.MAIN GATE","I.C.F","ICF ANNEXE","I.C.F.COLONY","I.C.I.","ILLALUR JUNCTION","ILLANTHOPE","INAM AGARAM","INDIRA NAGAR","INDIRA NAGAR WATER TANK","INJAMBAKKAM","I.O.C","IRANKUPPAM","I.R.T. RD.JN.","IRULAPALAYAM","IRULAPALAYAM RD JN.","IRUMBULIYUR","IRUNKATTUKOTTAI","JAFFARKHAN PET","JAMALAYA","JEYAPURAM","JN.OF ALAPAKKAM & E.V.R.","JN.OF.ARTERIAL RD WITH 40","JN.OF CENTRAL AVENUE&ERIK;","JN OF III AND 1ST AVE","JN.OF MAMBAKKAM & O.BAKKA","JN.OF MAMBAKKAM RD & ATAN","JN.OF MANALI RD.CHINNA KO","JN.OF.ORAKADU RD & S/VARA","JN.OF.PALAVANTHANGAL &GST;","JN.","OF PONNERI RD","&ERANOO;","JN.OFPORUR POONAM WITH MA","Jn.OF P.T.R Rd/KAMARAJ Rd","JN.OF RACE COURSE RD","JN. OF R.GARDEN & PEVR H.","JN.OF.VLY-TBM RD&MVKM-K.K;","KADAMBATHUR","KADAPAKKAM","KADHAVOOR","KADHAVOOR RD.JN.","KAKKALUR","KAKKAN BRIDGE","KALAIGNAR NAGAR","KALAIGNAR NAGAR WEST","KALAVAKKAM TEA STALL","KALLIKALAM","KALLIKUPPAM","KAMABAR ARANGAM","KAMARAJAPURAM","KAMARAJ NAGAR","KANATHUR","KANCHIVOYAL","KANDANCHAVADI","KANDAN KOLLAI","KANDASAMY NAGAR","KANDIGAI","KANNADAPALAYAM","KANNAGI NAGAR S.C.BOARD","KANNAN THEATER","KANNIAMMAN NAGAR","KANNIAMPALAYAM","KANNIGAIPEIR","KANNI KOIL","KANNIVAKKAM","KARAKKU","KARANAI","KARANODAI","KARANODAI SCHOOL","KARAPAKKAM","KARASANGAL","KARAYANCAHVADI","KARGIL NAGAR","KARIMEDU","KARUMANOOR KANDIGAI","KARUMBAKKAM","KARUNGUDI PALLAM","KASANOOR","KATHIRVEDU","KATTU KOOT ROAD","KATTUR","KATTUR CROSS ROAD","KATTUR ROAD JN.","KAVALPATHY","KAVANGARAI","KAVANOOR","KAVANOOR KOOT ROAD","KAVARAIPALAYAM","KAVARAPED","KAVIARASU KANNADASAN NAGA","KAYAAR","KEERAPAKKAM","KELAMBAKKAM","KELLEYS","KESAVA CROSS ROAD","KILKATTALAI","KILKONDAIYUR","KILPAUK GARDEN","KIZHANOOR","KIZHKALVOY","KIZH NALLATHUR","KIZHUR","K.M.C","KODUNGAIYUR O.T.","KODUNGAIYUR(PARVATHI NAGA","KODUNGAIYUR PARVATHINAGAR","KOILPATHAGAI RD.JN.","KOLADI SCHOOL","KOLAPAKKAM","KOLAPAKKAM COLONY","KOLAPAKKAM RICE MILL","KOLAPPANCHERY","KOLATHUR","KOLATHUR/NEHRU RD JN","KOLLAICHERI","KOMAN NAGAR RD JN.","KONDAKKARAI","KONDANCHERY CHRISTHUVA SA","KONIMEDU RD. JN.","KOOTHAVAKKAM SCHOOL","KOOVAM","KOOVOOR","KORATTUR","KORUKKUPET","KORUKKUPET R.S","KOSAPALAYAM","KOSAPPUR","KOSAPPUR PUO","KOSAPUR RD. JN.","","KOSAVAMPETTAI","KOSAVAN PALAYAM","KOTHARI","KOTTIVAKKAM","KOTTUR NSK STATUE","KOTTURPURAM","KOTYAMEDU","KOVALAM","KOVILAMCHERRY VILLAGE","KOYAMBEDU P.S","KOYAMBEDU ROHINI THEATER","KOYAMBEDU SCHOOL","KOYMABEDU MARKET","KRISHNA KARANAI","KRISHNAN TEMPLE/PONDY BAZ","KRISHNAPURAM","KUMARAN KUNDRAM","KUMARAN NAGAR","KUMMANUR","KUMUNANCHAVADI","KUNDRATHUR B.S","KUNDRATHUR MURUGAN TEMPLE","KUNNAVAKKAM","KUPPAMMAL CHATHIRAM","KUTHANOOR ROAD JN.","LADY MCTM SCHOOL/MILLERS","LATTICE BRIDGE","LATTICE BRIDGE RD. JN.","LUCAS TVS","LUZ","MADAMBAKKAM","MADAMBAKKAM KOIL","MADANAKUPPAM","MADANANADAPURAM","MADARAPAKKAM BUS TERMINUS","MADARAPAKKAM CROSS ROAD","MADHAVARAM","BUS BAY-17TH KM","MADHAVARAM MILLK COLONY","MADHAVARAM POST BOX","MADAHVARAM VILLAGE","MADIPAKKAM B.S","MADIPAKKAM KOOT ROAD","MADIPAKKAM RD. JN.","MADURAPAKKAM","MADURAPAKKAM RD.JN.","MADURAVOYAL","MAGARAL KANDIGAI","MAHAKAVI BHARATHI NAGAR","MAHALAKSHMI NAGAR","MAHALINGAPURAM","MAHARANI","MAHENDRA CITY(CHETTY PUNN","MALAI PATTU","MALLIGAI NAGAR AVE","MALROSAPURAM","MAMALLAPURAM","MAMBAKKAM","MAMBAKKAM RDJN./VENKATAMA","MAMBAKKAM ROCE MILL","MAMBAKKAM TEMPLE","MANALAI SEEKADU","MANALI","MANALI NEW TOWN","MANALI RD JN.","MANAMATHI","MANAMATHI JN.","MANAMATHI KOOT RD","MANAMATHI SCHOOL","MANAPAKKAM P.U.O","MANAPAKKAM VILLAGE","MANAVALAN NAGAR","MANCHANKARANAI","MANDAVELI","MANGADU","MANIMANGALAM","MANIMANGALAM RD. JN.","MANIMANGALAM VILLAGE","MANIVAKKAM","MANNIVAKKAM ROAD JN.","MANNUR VILLAGE","MARAIMALAI NAGAR","MARAIMALAI NAGAR I.E.","MATERNITY HOSPITAL","MATHUR","MATHUR M.M.D.A.","MATHUR RD. JN.","","MATHUR VILLAGE","MEDAVAKKAM","MEDAVAKKAM COLONY","MEDAVAKKAM JN.","MEDHUR","MELAPEDU","MEL AYANAMBAKKAM","MELKALVOY","MELKONDAIYUR","MELKOTTIYUR","MELMALLIKAIPATTU","MELNALLATHUR","MELPAKKAM","MENAMABAKKAM OLD AIRPORT","MENAMBEDU","MEPPADU HOSPITAL","MEPPEDU","MEPPEDU KOOT RD","MEPPUR","METTUKANDIGAI","METTUPALAYAM","MEYYUR","M.G.R.NAGAR","MILLERS ROAD","MINJUR","MINJUR B.D.O","MINJUR NEW TERMINUS","MINJUR R.S","M.K.B.NAGAR","M.K.B.NAGAR EAST","M.M.C","M.M.D.A.COLONY","M.M.D.A.COLONY RD.JN.","MOGAIPAIR ROAD JN.","MOGALIVAKKAM","MOGALIVAKKAM / MARI AMMN","MOGALIVAKKAM RD. JN.","MOGAPAIR","MOGAPAIR EAST","MOGAPAIR OFF.COL","MOGAPAIR ROAD JN","MOGAPAIR WEST","MOOLAKADAI","MOOLAKARAI","MOOTAKARAN CHAVADI","MOOVARASANPET","MORAI","MOSQUE","MOULIVAKKAM","MUDHUKUR CROSS ROAD","MUDICHUR","MUDICHUR VILLAGE","MULLAI NAGAR","MURUGAN KOIL / GIRUGAMBAK","MURUKKANCHERI","MUTHAMIL NAGAR","MUTHAPUDUPET","MUTHUMARIAMMAN KOIL","MUTTUKKADU","MUTTUKKADU BOAT YARD","MYLAI KOOT ROAD","MYLAPORE","N4 POLICE STATION","NADUVANKARAI","NADUVEERAPATTU","NAGALKENI","NALLUR","NALLUR PUDU NAGAR","NANDAMBAKKAM","NANDAMBAKKAM KALAIGNAR NA","NANDAMBAKKAM VILLAGE","NANGANALLUR","NANMABGALAM RD. JN.","NAPALAYAM","NARAYANAPURAM","NASIC NAGAR","NATHAMBEDU COLONY","NATHAMBEDU ROAD JN.","NATHAMUNI TALKIES","NATHATHANALLUR","NATIONAL HIGH SCHOOL","NATURE CARE HOSPITAL","NAVALUR","NAZARATH","NAZARATHPET","NEDUGUNDRAM","NEELANKARAI","NEHRU NAGAR","NEITHAVOYAL","NELLIKUPPAM","NEMAM","NEMILICHERI","NERKUNDRAM","NEW ERUMAI VETTI PALAYAM","NEW NAGAR","NEW ROAD","N.G.O.COLONY","NOOKAMPALAYAM VILLAGE","NOOTHANCHERI","NOOTHANCHERI CROSS RD.","N.S.K NAGAR","NUCLEUS COMPANY","NUNGAMBAKKAM R.S","ODEON MANI","OIL MILL","OLD ERUMAI VETTI PALAYAM","OLD&NEW; ERUMAI VETTI PALA","OONAMANCHERI","OORAPAKKAM SCHOOL","OOTHUKADU CROSS ROAD","ORAGADAM","ORAGADAM KOOT ROAD","ORAGADAM O.T.","ORAKKADU","OTTIAMBAKKAM","P1.POLICE STATION","P1 P.S","PADAPPAI","PADI KUPPAM","PADIYANALLUR","PADURMEDU","PAGALMEDU","PAKKAM","PAKKAM VILLAGE","PALAKKA COMPANY","PALAVAKKAM","PALAVAKKAM CROSS ROAD","PALAVASTHIC CHEMICALS","PALAVEDU","PALLAVAN NAGAR","PALLAVARAM","PALLAVARAM GATE","PAMMADUKULAM","PAMMADUKULAM COLONY","PAMMADU KULAM RD.JN.","PAMMAL","PAMMAL SANKAR NAGAR","PANAIYUR","PANAPAKKAM","PANAPAKKAMEDU","PANCHALAI","PANDESWARAM","PANDITHAMEDU","PANDUR","PANDY KAVANOOR JN.","PANJETTI","PANRUTTI","PAPPANCHATRAM","PARANIPUTHUR","PARIVAKKAM","PARRYS","PARUTHIPATTU RD. JN.","PATTABIRAM","PATTAMANDIRI","PATTIKULAM COLONY","PATTUNOOL CHATRAM","PATTUR","PAVENTHER SALAI","PAYYANOOR","PAZAVANTHANGAL ROAD JN.","PAZHANTHANDALAM","PAZHANTHANDALAM ROAD JN.","PAZHAVERKADU","PEAVALLUR KUMARAN NAGAR","PENNALUR E.B.","PERAMBAKKAM","PERAMBUR B.S","PERAMBUR MARKET","PERAMBUR R.S","PERIAMULLAIVOYAL","PERIYA KOTTAMEDU","PERIYAL NEMBILI VILLAGE","PERIYAPALAYAM","PERIYAPALAYAM RD JN.","PERIYAPALAYAM TEMPLE","PERIYAPANICHERI","PERIYAR BRIDGE","PERIYAR NAGAR","PERLIYAMBAKKAM","PERUMAL KOIL","PERUMAL NAGAR JN.","PERUMALPATTU","PERUMATHUNALLUR","PERUMBAKKAM COLONY(INDRAN","PERUMBAKKAM LIMIT","PERUMBUR","PERUNGALATHUR (OLD)","PERUNGAVOOR","PERUNGULATHUR","PERUNTHANDALAM","PERUVOYAL","PICTURE POST","PILLAIPAKKAM","PILLAIPAKKAM KOOT ROAD","POGALMEDU","POLICE QUARTERS","POLIVAKKAM","POLLACHIAMMANKULAM","POLYTECHNIC","PONDY BAZAAR","PONMAR","PONNERI","PONNIAMMAN KOIL RD. JN.","POOCHIATHIBEDU","POOMBUHAR","POONAMALLEE","POONCHERY KOOT ROAD","POONDI","POONDI KOOT ROAD (NEYVELI","POONGERI JN.","POONTHANDALAM","POONTHANDALAM RD.JN.","POOVALAMBEDU","POOVALLI KUPPAM","P.OR & SONS","PORUR","POSTAL AUDIT OFFICE","POTHUR","POZHAL","POZHAL CAMP","POZHICHALUR","PRITHIYANGARA DEVI TEMPLE","PRIYAN KUPPAM","PTC QUARTER / ESWARANTEMP","PUDUKUPPAM","PUDUPAKKAM","PUDUPEIR COOT ROAD","PUDUR","PUDUR HIGH SCHOOL","PUDUVOYAL","PULICUT PANCHAYAT LIMIT","PULIKULAM","PULIPAKKAM","PULIYUR","PULIYUR KANDIGAI","PULLARAMBAKKAM","PUSHPAGIRI","PUSHPAGIRI RD. JN.","PUSHPA NAGAR","PUTHUCHATHIRAM","PUZHITHIVAKKAM B.S","Q.M.ARTS COLLEGE","Q.M ARTS (MEN)","Q.M.C","RAJAPALAYAM","RAMACHANDRA MEDL.COLLEGE","RAMAPURAM","RAMAPURAM (L.N.P KOIL)","RAMASAMY NAGAR","RANGARAJAPURAM","RED HILLS","REGAL","RETTAMBEDU","ROYAPETTA HOSPITAL","ROYAPURAM","ROYAPURAM P.S","R.R.KANDIGAI","SADANANDAPURAM","SADURANGAPETTAI","SAIDAPET","SAIDAPET WEST","SAKTHI NAGAR","SAKTHI VINAYAGAR KOIL","SALAMANGALAM KOOT ROAD","SALAVANKUPPAM/DEVANORI","SALIGRAMAN","SALT OFFICE","SAMIYAR PANNAI","SANTHOME P.O","SARAPANCHERY","SARMA NAGAR","SATHANKUPPAM","SATHIYAMOORTHY NAGAR","SATHIYAVEDU KOOT ROAD","SAYANI/AYNAVARAM","SCREW FACTORY","SCULPTURE ARTS COLLEGE","SECRETARIAT","SECRETARIAT COLONY","SEMILIVARAM","CHEMMANCHERI KUPPAM","CHEMMAN CHERI","CHEMMANCHERY S.C.B.","SENKADU","SENNEERKUPPAM","SENTHIL NAGAR","SETTIMEDU","SHANTHI/DAMS RD.","S.H.B","SHIVASHANMUGAPURAM","SHOLAVARAM","SHOLAVARAM P.S.","SIDCO","SIDCO NAGAR","SIKKARAVARAM","SIKKARAYAPURAM","SIPCOT","SIRUCHERI","SIRUKALATHUR","SIRUKUNDRAM KOOT ROAD","SIRUNIAM RD.JN.","S.I.V.E.T","SLUM CLEARANCE BOARD","SOMANGALAM","SOMANGALAM RD /AMARAMBEDU","SOMANGALAM RD JN/N.V.R.D.","SONALUR / PUDUR","SOTHUPERMEDU","SOUTH BOAG & S.EAST BOAG","SOWBAKKIYA NAGAR","SOZHINGANALLUR P.U.OFFICE","SOZHIPALAYAM","S.P.KOIL","SRINIVASA NAGAR","SRINIVASA THEATER","SRIPERUMPUDUR","SRI RAM ENGG.COLLEGE","SRI SANKARA HEALTH CENTRE","SRIUNGAVOOR","S.R.P. COLONY","SRP TOOLS","STEPHEN CHURCH","STERLING Rd/METEOROLOGY D","STERLING RD./METROLOG. DE","STERLING ROAD","ST THOMAS MOUNT","ST THOMAS MOUNT PO","ST THOMAS MOUNT R.S","SULERIKADU","SUMENTHIRAMEDU KOOT ROAD","SUNDARASOZHAPURAM","SUNGUVARCHATHIRAM","SUNNAMBU KALVOY","SUNNAMBU KOLATHUR","SUN THEATER","SURAPEDU","T.ACHARAVAKKAM","TAMARAIPAKKAM","TAMARAIPAKKAM RD.JN.","TAMARIND TREE","TAMBARAM","TAMBARAM EAST","TAMBARAM TOWN LIMIT","TARAMANI","TAYLORS ROAD","TB HOSPITAL","T.B.INSTITUTE","T.B.SANATORIUM","TEACHERS COLONY","TELEGRAPH OFFICE","THAILAPURAM","THALAMBUR","THAMBUCHETTY ST","THANDALACHERI","THANDALAM","THANDALAM KOOT ROAD","THANDALAM RD JN.","THANDALAM VILLAGE","THANDARAI","THANGAL","THANI POONDI","THANTHONI AMMAN NAGAR","THARATCHI COLONY","THATCHUR KOOT ROAD","THATHANMANJI","THAZHAMBEDU","THAZHANKUPPAM","THEAGARAYA COLLEGE","THERASAPURAM","THEVERIPAKKAM","THEYAMPAKKAM","THILLAI GANGA NAGR IIND M","THILLAIGANGA NAG SUB.3rdM","THIRUMALISAI","THIRUMANGALAM","THIRUMUDIVAKKAM","THIRUMULLAIVOAYL","THIRUNEERMALAI","THIRUNILLAI RD.JN.","THIRUNINDRAVOOR","THIRUNINDRAVOOR P.U.O.","THIRUNINDRAVOOR RLY.STN.","THIRUPALAIVANAM","THIRUPATCHUR","THIRUPPORUR","THIRUSOOLAM NATIONAL AIRP","THIRUTHUVELI","THIRUVALLUR","THIRUVANMIYUR","THIRUVEDANTHAI","THIRUVENGADAPURAM","THIRUVERKADU","THIRUVETRIYUR B.S","THIRUVOTRIYUR TEMPLE","THOMMARAM BEDU","THORAPPAKKAM P.T.C COLONY","THORAPPAKKAM TEA SHOP","THOZHUDUR","THRUVOTRIYUR TEMPLE","THUMBAKKAM","T.NAGAR BUS TERMINUS","T.N.C.F","TOLLGATE","TOLLGATE(SATHIAVEDU KOOT","TONDAIAYRPET","TRAVELLERS BANGALOW","TRIPLICANE","TRIPLICANE O.T (CORPN. SC","TRUSTPURAM","TSR RAJALAKSHMI NAGAR","T.V.K.NAGAR","T.V.S","T.V.T RLY GATE","U.MANDAVELI","UNIVERCITY CLUB","UPPALAYAM","UPPARA PALAYAM","U.S.I.S.","UTHAMAR GANDHISALAI (CORP","UTHANDI VILLAGE","UTHUKKOTTAI","VAANAGARAM","VADAMADURAI","VADAMADURAI KANDIGAI","VADAMANGALAM KOOT ROAD","VADANEMILI","VADAPALANI B.S","VADAPALANI JN.","VADAPALANI P.S","VADAPERUMBAKKAM","VADHATTUR JN.","VALARPURAM","VALASARAVAKKAM","VALLAKKOTTAI","VALLAM","VALLIYUR SCHOOL","VALLUVARKOTTAM","VANDALOOR","VANDALOOR RD.JN","VANDALOOR R.G/MANIVAKKAM","VANDALOOR ZOO","VANJIVANCHERY","VANUVAMBEDU","VARADARAJA PURAM","VARADHARAJA THEATER","VARANAVASI","VASANTHI AMMAN KOIL","VATTAMBAKKAM","VAYALUR","VAYALUR CROSS ROAD","VAZHUTHALAMBEDU","VAZHUTHALAMBEDU RD. JN","VAZHUTHUNAIMEDU","VEENUS","VEERABADRA NAGAR","VEERAPURAM","VEERAPURAM RD JN.","VELACHERY","VELACHERY HOSPITAL","VELACHERY VIJAYA NAGAR","VELANGADUPAKKAM","VELAPPANCHAVADI","VELLAIKAL","VELLAVEDU","VEMBAKKAM","VEMBEDU","VENGADU KOOT ROAD","VENGAIVASAL P.H.CENTRE","VENGAIVASAL RD.JN.","VENGAL","VENGAL CROSS ROAD","VENGAMBAKKAM","VENGAMBAKKAM RD JN.","VENGAMBAKKAM VILLAGE","VENGATAPURAM","VENGOOR JUNCTION","VENKATAMANGAM","VENKATHAKULAM","VENKATHUR","VEPPAMPATTU","VEPPAMPATTU ESWARAN NAGAR","VEPPAMPATTU R.S.","VEPPUMPATTU PULIYAMARAM","VERKADU","VETERINARY HOSPITAL","VETERINARY HOSPITAL/PRDCT","VETTUVANKANNI","V.HOUSE","V.HOUSE P.S","V.HOUSE TERMINUS","VICHOOR","VICTORIA TEACHERS COLONY","VIDYODAYA","VIJAYA NAGAR","VILAMBAKKAM","VILINJAMBAKKAM AMMAN KOIL","VILLIVAKKAM","VINAYAGAPURAM","VINAYAGAR KOIL","VIRUGAMBAKKAM","VISHNUVAKKAM","VIVEK & CO (KRISHNAN KOIL","V.M.STREET","V. NAGAR","V.S.B.GARDEN","VYASARPADI","WALLAJABATH","WATER PIPE THANTHANKUPPAM","WATER SUPPLY HEAD WORK","WEELS INDIA RD.JN.","WESLEY H.S","WOMENS POLYTECHNIC","Y.M.I.A"};
	
	
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		
		if(iflag!=1 && android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.KITKAT)
		{
			@SuppressWarnings("deprecation")
			String providers = Secure.getString(this.getContentResolver(),
	                Secure.LOCATION_PROVIDERS_ALLOWED);
	        if (TextUtils.isEmpty(providers))
			 buildAlertMessageNoGps(1);
		}
			 else
			 {
		 int locationMode=0;
			        try {
			            locationMode = Secure.getInt(this.getContentResolver(),
			                    Secure.LOCATION_MODE);
			        } catch (SettingNotFoundException e) {
			            e.printStackTrace();
			            
			        }
			        if(locationMode!=Secure.LOCATION_MODE_HIGH_ACCURACY)
				 buildAlertMessageNoGps(0);
			 }
		
		AutoCompleteTextView to = (AutoCompleteTextView) findViewById(R.id.to);
		AutoCompleteTextView from = (AutoCompleteTextView) findViewById(R.id.from);
		    		
		        	ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, R.layout.my_list_view, stops);
		        	to.setAdapter(adapter);
		        	from.setAdapter(adapter);
	}

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		// Inflate the menu; this adds items to the action bar if it is present.
		getMenuInflater().inflate(R.menu.main, menu);
		return true;
	}

	protected void onActivityResult(final int requestCode, final int resultCode, final Intent intent1)
  	 {
  	     if (resultCode == Activity.RESULT_OK && requestCode == 5)
  	     {
  	          Uri uri = intent1.getParcelableExtra(RingtoneManager.EXTRA_RINGTONE_PICKED_URI);

  	          if (uri != null)
  	          {
  	              RingtoneManager.setActualDefaultRingtoneUri(getBaseContext(), 1, uri) ;
  	          }
  	          else
  	          {
  	              
  	          }
  	      }            
  	  }

	
	public boolean onOptionsItemSelected(MenuItem item) {
		
	
			switch (item.getItemId()) {
	        case R.id.action_settings:
			Intent intent=new Intent(this,ShowAlarms.class);
		startActivity(intent);
		return true;
	        case R.id.action_settings2:
	        	
	        	Intent intent1 = new Intent(RingtoneManager.ACTION_RINGTONE_PICKER);
	        	intent1.putExtra(RingtoneManager.EXTRA_RINGTONE_TYPE, RingtoneManager.TYPE_RINGTONE);
	        	intent1.putExtra(RingtoneManager.EXTRA_RINGTONE_TITLE, "Select Tone");
	        	intent1.putExtra(RingtoneManager.EXTRA_RINGTONE_EXISTING_URI, (Uri) null);
	        	this.startActivityForResult(intent1,5);
	        	
	        	
	        	
	        	return true;
			}
			return true;
	}
	
	
	public void findRoute(View view) {
		AutoCompleteTextView textView = (AutoCompleteTextView) findViewById(R.id.to);
		AutoCompleteTextView textView2 = (AutoCompleteTextView) findViewById(R.id.from);
		String dstop = textView.getText().toString();
		String sstop = textView2.getText().toString();
        
		int flag1=0,flag2=0;
		for(int i=0;i<stops.length;i++)
		{
			if(dstop.equals(stops[i]))
				flag1=1;
			if(sstop.equals(stops[i]))
				flag2=1;
			
		}
		
		if(dstop.equals("") || sstop.equals("") ||flag1!=1 || flag2!=1)
		{
			Toast.makeText(this, "choose correct bus stops", Toast.LENGTH_LONG).show();
			
		}
		else
		{
        Intent intent = new Intent(this, DisplayMessageActivity.class);
        intent.putExtra(DEST_STOP, dstop);
        intent.putExtra(SRC_STOP, sstop);
    	startActivity(intent);
		}
		}
public void find(View view)
{
	int flag=0;
	ImageView i=(ImageView)findViewById(R.id.imageView1);
	i.setVisibility(View.VISIBLE);
	if(android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.KITKAT)
	{
		@SuppressWarnings("deprecation")
		String providers = Secure.getString(this.getContentResolver(),
                Secure.LOCATION_PROVIDERS_ALLOWED);
        if (TextUtils.isEmpty(providers))
        {
        	flag=1;
		 buildAlertMessageNeedsGps(1);
        i.setVisibility(View.INVISIBLE);
        }
	}
		 else if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT)
		 {
	 int locationMode=0;
		        try {
		            locationMode = Secure.getInt(this.getContentResolver(),
		                    Secure.LOCATION_MODE);
		        } catch (SettingNotFoundException e) {
		            e.printStackTrace();
		            
		        }
		        if(locationMode!=Secure.LOCATION_MODE_HIGH_ACCURACY)
		        {
		        	flag=1;
		        	i.setVisibility(View.INVISIBLE);
		        	buildAlertMessageNeedsGps(0);
		        }
		 }
	
		 if(flag==0)
		 {

			 final Intent intent = new Intent(this, CheckBus.class);
	Toast.makeText(this, "fetching gps information", Toast.LENGTH_LONG).show();
			 mHandler.postDelayed(new Runnable() {
			        public void run() {
						startActivity(intent);
								           
			        }
			    }, 2000);
				   	 
		 }
	
	
    }

@Override
public void onResume(){
super.onResume();
	ImageView i=(ImageView)findViewById(R.id.imageView1);
	i.setVisibility(View.INVISIBLE);

}

	
}
